"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-01

Creates the full PeopleDesk schema and enables the pgvector extension.
Hand-authored (not autogenerated) so it is fully reproducible without a
live database. Keep in sync with app/models/*.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TS = dict(server_default=sa.text("now()"), nullable=False)


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), **TS),
        sa.Column("updated_at", sa.DateTime(timezone=True), **TS),
    ]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    rbac_role = sa.Enum("employee", "manager", "hr_admin", "super_admin", name="rbac_role")
    employment_status = sa.Enum("active", "on_leave", "terminated", name="employment_status")
    leave_status = sa.Enum("pending", "approved", "rejected", "cancelled", name="leave_status")
    policy_status = sa.Enum("draft", "published", name="policy_status")

    # --- department ---
    op.create_table(
        "department",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(120), nullable=False, unique=True),
        *_timestamps(),
    )

    # --- employee (self-referential manager FK) ---
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("first_name", sa.String(80), nullable=False),
        sa.Column("last_name", sa.String(80), nullable=False),
        sa.Column("work_email", sa.String(255), nullable=False, unique=True),
        sa.Column("title", sa.String(120), nullable=False),
        sa.Column("location", sa.String(120), nullable=False, server_default="Remote"),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("employment_status", employment_status, nullable=False, server_default="active"),
        sa.Column("department_id", sa.Integer(), sa.ForeignKey("department.id", ondelete="SET NULL"), nullable=True),
        sa.Column("manager_id", sa.Integer(), sa.ForeignKey("employee.id", ondelete="SET NULL"), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_employee_work_email", "employee", ["work_email"])
    op.create_index("ix_employee_department_id", "employee", ["department_id"])
    op.create_index("ix_employee_manager_id", "employee", ["manager_id"])

    # --- user_account ---
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("rbac_role", rbac_role, nullable=False, server_default="employee"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employee.id", ondelete="SET NULL"), nullable=True, unique=True),
        *_timestamps(),
    )
    op.create_index("ix_user_account_email", "user_account", ["email"])

    # --- leave_type ---
    op.create_table(
        "leave_type",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(60), nullable=False, unique=True),
        sa.Column("code", sa.String(20), nullable=False, unique=True),
        sa.Column("annual_accrual_days", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("description", sa.String(255), nullable=False, server_default=""),
        *_timestamps(),
    )

    # --- leave_balance ---
    op.create_table(
        "leave_balance",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employee.id", ondelete="CASCADE"), nullable=False),
        sa.Column("leave_type_id", sa.Integer(), sa.ForeignKey("leave_type.id", ondelete="CASCADE"), nullable=False),
        sa.Column("accrued", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("used", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.UniqueConstraint("employee_id", "leave_type_id", name="uq_balance_employee_type"),
        *_timestamps(),
    )
    op.create_index("ix_leave_balance_employee_id", "leave_balance", ["employee_id"])
    op.create_index("ix_leave_balance_leave_type_id", "leave_balance", ["leave_type_id"])

    # --- leave_request ---
    op.create_table(
        "leave_request",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employee.id", ondelete="CASCADE"), nullable=False),
        sa.Column("leave_type_id", sa.Integer(), sa.ForeignKey("leave_type.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("days", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("reason", sa.String(1000), nullable=False, server_default=""),
        sa.Column("status", leave_status, nullable=False, server_default="pending"),
        sa.Column("approver_id", sa.Integer(), sa.ForeignKey("employee.id", ondelete="SET NULL"), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.String(1000), nullable=False, server_default=""),
        sa.Column("created_via_agent", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_timestamps(),
    )
    op.create_index("ix_leave_request_employee_id", "leave_request", ["employee_id"])
    op.create_index("ix_leave_request_leave_type_id", "leave_request", ["leave_type_id"])
    op.create_index("ix_leave_request_approver_id", "leave_request", ["approver_id"])

    # --- policy_document ---
    op.create_table(
        "policy_document",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("category", sa.String(120), nullable=False, server_default="General"),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("status", policy_status, nullable=False, server_default="draft"),
        sa.Column("effective_date", sa.Date(), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_policy_document_title", "policy_document", ["title"])

    # --- policy_chunk (vector embeddings) ---
    op.create_table(
        "policy_chunk",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("policy_document_id", sa.Integer(), sa.ForeignKey("policy_document.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("doc_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("doc_title", sa.String(255), nullable=False, server_default=""),
        sa.Column("embedding", Vector(384), nullable=False),
        *_timestamps(),
    )
    op.create_index("ix_policy_chunk_policy_document_id", "policy_chunk", ["policy_document_id"])

    # --- agent_conversation ---
    op.create_table(
        "agent_conversation",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_account.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title", sa.String(255), nullable=False, server_default="New conversation"),
        *_timestamps(),
    )
    op.create_index("ix_agent_conversation_user_id", "agent_conversation", ["user_id"])

    # --- agent_message ---
    op.create_table(
        "agent_message",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("conversation_id", sa.Integer(), sa.ForeignKey("agent_conversation.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False, server_default=""),
        sa.Column("tool_calls", postgresql.JSONB(), nullable=True),
        sa.Column("sources", postgresql.JSONB(), nullable=True),
        *_timestamps(),
    )
    op.create_index("ix_agent_message_conversation_id", "agent_message", ["conversation_id"])

    # --- hr_ticket ---
    op.create_table(
        "hr_ticket",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("raised_by_user_id", sa.Integer(), sa.ForeignKey("user_account.id", ondelete="CASCADE"), nullable=False),
        sa.Column("category", sa.String(40), nullable=False, server_default="general"),
        sa.Column("summary", sa.Text(), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        *_timestamps(),
    )
    op.create_index("ix_hr_ticket_raised_by_user_id", "hr_ticket", ["raised_by_user_id"])

    # --- audit_log (append-only) ---
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("actor_user_id", sa.Integer(), sa.ForeignKey("user_account.id", ondelete="SET NULL"), nullable=True),
        sa.Column("action", sa.String(120), nullable=False),
        sa.Column("entity_type", sa.String(80), nullable=False, server_default=""),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    op.create_index("ix_audit_log_actor_user_id", "audit_log", ["actor_user_id"])
    op.create_index("ix_audit_log_action", "audit_log", ["action"])
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"])


def downgrade() -> None:
    for tbl in [
        "audit_log",
        "hr_ticket",
        "agent_message",
        "agent_conversation",
        "policy_chunk",
        "policy_document",
        "leave_request",
        "leave_balance",
        "leave_type",
        "user_account",
        "employee",
        "department",
    ]:
        op.drop_table(tbl)
    for enum_name in ("rbac_role", "employment_status", "leave_status", "policy_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
